# Generated by Django 6.1 on 2026-08-26 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-rating', 'name']},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'ordering': ['time']},
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(default=120, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Crime', 'Crime'), ('Mystery', 'Mystery')], default='Action', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('Spanish', 'Spanish'), ('French', 'French')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi-NCR', 'Delhi-NCR'), ('Bengaluru', 'Bengaluru'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Ahmedabad', 'Ahmedabad')], default='Mumbai', max_length=100),
        ),
        migrations.AddField(
            model_name='theater',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='theater',
            name='theater_chain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to='movies.movie')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
