# Generated by Django 6.1 on 2026-08-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_herobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Hero Banner Slide', 'verbose_name_plural': 'Hero Banner Slides'},
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='link_url',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='badge',
            field=models.CharField(blank=True, help_text="Small badge label e.g. 'Now Trending'", max_length=80),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='badge_color',
            field=models.CharField(choices=[('danger', 'Red (Now Trending)'), ('warning', 'Yellow (Top Rated)'), ('info', 'Blue (Multi-City)'), ('success', 'Green (New Release)'), ('primary', 'Blue (Feature)')], default='danger', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='button_url',
            field=models.CharField(default='/movies/', help_text='URL the button links to', max_length=255),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_text',
            field=models.CharField(default='Explore Movies', max_length=80),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='image',
            field=models.ImageField(help_text='Upload hero background image (recommended: 1240×300px or 16:9)', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this slide'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first (0, 1, 2 ...)'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle',
            field=models.CharField(default='', help_text='Short description under the title', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=models.CharField(help_text='Main heading text shown on the slide', max_length=200),
        ),
    ]
