# Generated by Django 5.1.1 on 2026-08-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_hero_banner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique booking reference code (e.g. PMS-2026-XXXXX)', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Payment transaction reference ID', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='theater',
            name='screen_name',
            field=models.CharField(default='Screen 1 (Audi 1)', help_text='Auditorium or screen name', max_length=100),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='badge',
            field=models.CharField(blank=True, default='', help_text="Small badge label e.g. 'Now Trending'", max_length=80),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Short description under the title', max_length=300),
        ),
    ]
