# Generated by Django 5.1.1 on 2026-09-07 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_booking_booking_id_booking_email_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='fa-film', help_text='FontAwesome icon name e.g. fa-film, fa-fire, fa-laugh', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='ISO code e.g. en, hi, ta, te', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='age_certification',
            field=models.CharField(choices=[('U', 'U (Universal - All Ages)'), ('UA 7+', 'UA 7+ (Parental Guidance for under 7)'), ('UA 13+', 'UA 13+ (Parental Guidance for under 13)'), ('UA 16+', 'UA 16+ (Parental Guidance for under 16)'), ('A', 'A (Adults Only 18+)'), ('PG-13', 'PG-13 (Parents Strongly Cautioned)'), ('R', 'R (Restricted 17+)')], default='UA 13+', help_text='Censor rating / age certification', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='Director name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='synopsis',
            field=models.TextField(blank=True, help_text='Detailed storyline and synopsis', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='YouTube trailer URL e.g. https://www.youtube.com/watch?v=... or embed link', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('Lead Actor', 'Lead Actor'), ('Lead Actress', 'Lead Actress'), ('Supporting Actor', 'Supporting Actor'), ('Supporting Actress', 'Supporting Actress'), ('Director', 'Director'), ('Music Director', 'Music Director'), ('Producer', 'Producer'), ('Writer', 'Writer'), ('Cinematographer', 'Cinematographer')], default='Lead Actor', max_length=100)),
                ('character_name', models.CharField(blank=True, help_text='Character name (e.g. Neo, Cooper)', max_length=200, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='cast/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0=first)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='movies.movie')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Associated genre categories', related_name='movies', to='movies.genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Available languages', related_name='movies', to='movies.language'),
        ),
        migrations.CreateModel(
            name='MoviePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='movies/posters/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary display poster')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='movies.movie')),
            ],
            options={
                'ordering': ['order', '-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1/10 Stars'), (2, '2/10 Stars'), (3, '3/10 Stars'), (4, '4/10 Stars'), (5, '5/10 Stars'), (6, '6/10 Stars'), (7, '7/10 Stars'), (8, '8/10 Stars'), (9, '9/10 Stars'), (10, '10/10 Stars')], help_text='Rating on a 1-10 scale')),
                ('headline', models.CharField(blank=True, help_text='Summary / title of your review', max_length=200)),
                ('review_text', models.TextField(help_text='Detailed feedback and thoughts about the movie')),
                ('is_verified_viewer', models.BooleanField(default=True, help_text='Indicates the reviewer booked and watched the movie')),
                ('is_edited', models.BooleanField(default=False, help_text='True if review was edited after initial submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, help_text='Verified booking that unlocked this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='movies.booking')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SPAM', 'Spam, Advertising or Bots'), ('SPOILER', 'Contains Spoilers without warning'), ('OFFENSIVE', 'Offensive, Vulgar or Inappropriate Language'), ('HARASSMENT', 'Harassment, Hate Speech or Bullying'), ('FAKE', 'Fake or Irrelevant Content'), ('OTHER', 'Other Community Guideline Violation')], default='OFFENSIVE', max_length=30)),
                ('details', models.TextField(blank=True, help_text='Optional details explaining why this review was reported', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Moderation'), ('REVIEWED', 'Reviewed (Kept)'), ('ACTION_TAKEN', 'Action Taken (Review Removed)'), ('DISMISSED', 'Dismissed (Invalid Report)')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by moderator', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='movies.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('movie', 'user'), name='unique_movie_user_review'),
        ),
        migrations.AddConstraint(
            model_name='reviewreport',
            constraint=models.UniqueConstraint(fields=('review', 'reported_by'), name='unique_review_user_report'),
        ),
    ]
