# Generated by Django 6.1 on 2026-09-15 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_genre_language_movie_age_certification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, help_text='Unique booking ID reference code (e.g. PMS-2026-XXXXX)', max_length=50)),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], default='RAZORPAY', max_length=20)),
                ('order_id', models.CharField(db_index=True, help_text='Gateway Order ID (e.g. order_xxxx)', max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, help_text='Gateway Transaction ID (e.g. pay_xxxx)', max_length=100, null=True)),
                ('signature', models.CharField(blank=True, help_text='Cryptographic HMAC SHA256 signature from gateway', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount in INR (₹)', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=20)),
                ('seat_numbers', models.CharField(help_text='Comma-separated seat numbers (e.g. C1, C2)', max_length=255)),
                ('seat_ids', models.CharField(help_text='Comma-separated seat IDs for automatic release on failure', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='UPI/Card/Netbanking', help_text='Payment mode', max_length=50, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='movies.theater')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Payment transaction that confirmed this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='movies.paymenttransaction'),
        ),
    ]
