# Generated by Django 6.1 on 2026-09-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_seat_options_seat_reserved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='reservation_token',
            field=models.CharField(blank=True, db_index=True, help_text='Reservation session token tied to this checkout', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='reservation_token',
            field=models.CharField(blank=True, db_index=True, help_text='Cryptographic UUID4 reservation session token binding', max_length=64, null=True),
        ),
    ]
