# Generated by Django 6.1 on 2026-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_booking_booked_at_alter_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'price'], name='thtr_movie_price_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'time'], name='thtr_movie_time_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['city', 'time'], name='thtr_city_time_idx'),
        ),
    ]
